### PR TITLE
151 implement volunteer side home page

### LINKED ISSUE #151: Implement Volunteer side Home Page
image

- [Figma](https://www.figma.com/file/wD3jldG53uVqnUYDF5HcSs/Low-High-Fidelity-Wireframes?type=design&node-id=3357-16822&mode=design&t=iHY4QacxofrlGsb2-0)

# Description
- For this week, you guys will create a Volunteer side Home page
  - Make sure you sign in with volunteer account to work on this
- Almost identical to Admin's homepage
  - **Code**: `pages/HomePage.jsx`
  - **Page**: sign in with Admin account --> go to `localhost:3000/`
- Only exception is the `Impact Summary Dashboard` is different.
  - Create a new component `VolunteerImpactSummary.jsx`
  
# First Step:
## Create `pages/VolunteerHomePage.jsx` 
- Make a route in App.jsx to access this page when you're volunteer
- Hint: you can copy and paste Admin's Homepage and replace `ImpactSummary.jsx` with `VolunteerImpactSummary.jsx`

# `VolunteerImpactSummary.jsx`
## Total Event Participated Box
- Use backend route `Backend.get(`/data/volunteer/${volunteer.id}/event`);`
  - This retrieves a list of event names associated with the volunteerID
## Total Trash Weight Box
- Use backend route `Backend.get(`/data/volunteer/${volunteer.id}`)`
  - This retrieves all event_data related to volunteerID
  - Use `for (const { ounces, pounds } of response.data) {
        totalPounds += ounces / 16 + pounds;
      }` to get total Weight in Pounds

## Largest Trash Collected Box
- Use backend route `Backend.get(`/data/volunteer/${volunteer.id}`)`
- Find the `Maximum Weight` in here and display it

# Important:
- Make sure that the icons are correct
- Match Design

# Resources:
- [Figma](https://www.figma.com/file/wD3jldG53uVqnUYDF5HcSs/Low-High-Fidelity-Wireframes?type=design&node-id=3357-16822&mode=design&t=iHY4QacxofrlGsb2-0)

`

### PR DESCRIPTION
**Pull request by theNatePi**
## Changes
<details><summary>Volunteer Home Page</summary>
<p>

- Copied admin functionality onto volunteer-home route
- Removed selection and archiving functionality
- Maintained Search Location and Search Date functionality although it was not in design (I believe we talked about keeping this included before)
- Slightly change EventCard to match design on Figma
- Implement hamburger menu

image

image

</p>
</details> 

<details><summary>Impact Summary</summary>
<p>

- Implemented Impact Summary and proper icons
- Updated DataCard to match design

image
</p>
</details> 

## Testing
- Added line in VolunteerImpactSummary.jsx to set user ID to 111, this user has available events for testing values
    - image
- Implemented check for isNaN(largestItem) || !isFinite(largestItem) if provided weights are empty or invalid

### CODE REVIEW

File: src/components/Events/VolunteerImpactSummary.jsx [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+  const [total, setTotalPounds] = useState(0);
+  const [largestItem, setLargestItem] = useState(0);
+
+  const { user, updateUser } = useContext(UserContext);
+
+  useEffect(() => {
+    updateUser();
+    console.log(user);
+    getData();
+  }, []);
```
Comment (ctc-devops) [inline src/components/Events/VolunteerImpactSummary.jsx:19]: ⚠️ **[eslint]** <[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>React Hook useEffect has missing dependencies: 'getData', 'updateUser', and 'user'. Either include them or remove the dependency array.

File: src/pages/VolunteerHomePage.jsx [hunk 2]
```diff
@@ -0,0 +1,176 @@
...
+      if (ands.length > 0) {
+        const fuseResult = fuse.search({ $and: ands });
+        console.log(fuseResult);
+        // If we want to filter by score:
+        // result = fuseResult.filter(item => item.score <= 0.5).map(item => item.item);
+        result = fuseResult.map(item => item.item);
+      } else result = events;
+      console.log(result);
+      setDisplayEvents(result);
+    }, [name, location, date, fuse]);
```
Comment (ctc-devops) [inline src/pages/VolunteerHomePage.jsx:77]: ⚠️ **[eslint]** <[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>React Hook useEffect has a missing dependency: 'events'. Either include it or remove the dependency array.

**Review by NwinNwin — APPROVED** [review]
LGTM Tech lead
